/* Replace with your SQL commands */

CREATE TYPE USER_ROLE_TYPE AS ENUM ('ADMIN', 'USER');
CREATE TYPE CATEGORY_TYPE AS ENUM ('VEGETABLE', 'FRUIT', 'DAIRY', 'OTHERS');

CREATE TABLE accounts (
  id SERIAL PRIMARY KEY,
  password TEXT NOT NULL, 
  email TEXT UNIQUE NOT NULL, 
  role USER_ROLE_TYPE NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  last_login TIMESTAMP
);

CREATE TABLE items (
  id SERIAL PRIMARY KEY,
  name TEXT,
  price INTEGER NOT NULL,
  count INTEGER NOT NULL DEFAULT 0,
  category CATEGORY_TYPE NOT NULL,
  is_deleted BOOLEAN DEFAULT FALSE
);